/*
 * This file is generated by jOOQ.
 */
package org.jooq.meta.xugu.xugu;


import org.jooq.meta.xugu.xugu.tables.Proc;
import org.jooq.meta.xugu.xugu.tables.ProcsPriv;


/**
 * Convenience access to all tables in mysql.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Stored Procedures
     */
    public static final Proc PROC = Proc.PROC;

    /**
     * Procedure privileges
     */
    public static final ProcsPriv PROCS_PRIV = ProcsPriv.PROCS_PRIV;
}
