/*
 * This file is generated by jOOQ.
 */
package org.jooq.meta.xugu.xugu;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.jooq.meta.xugu.xugu.tables.Proc;
import org.jooq.meta.xugu.xugu.tables.ProcsPriv;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Xugu extends SchemaImpl {

    private static final long serialVersionUID = -1024895307;

    /**
     * The reference instance of <code>mysql</code>
     */
    public static final Xugu XUGU = new Xugu();

    /**
     * Stored Procedures
     */
    public final Proc PROC = Proc.PROC;

    /**
     * Procedure privileges
     */
    public final ProcsPriv PROCS_PRIV = ProcsPriv.PROCS_PRIV;

    /**
     * No further instances allowed
     */
    private Xugu() {
        super("mysql", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Proc.PROC,
            ProcsPriv.PROCS_PRIV);
    }
}
